### ISSUE TITLE
Technical Spike - cookies/localstorage with react/react-router

### ISSUE THREAD

**Issue by astroash** [astroash/policy-picker#6]
Cookies will allow us to only display the instruction modal the first time users use the site. Research needed to find out:
* how to set cookies in react/ react-router-dom
* how to interact with cookies in react/ react-router-dom

**Comment by maxgerber** [comment]
_Talk with Elias_:
+ Q: Is it possible to get cookies to talk to eachother within React?
A: I would just use localstorage which would be easier?

+ Q: Would this be a problem for browsers that don't support it?
A: As a proof of concept this wouldn't be a problem. It's also quite an old API so is quite widely supported.

+ If we were to go to the cookie route, on initial page load, we'd check for existence of the cookie, and serve loading view and a new cookie when it doesn't exist, or serve /home route otherwise. If it doesn't exists, we'd serve back the react app with a cookie. However cookies can't be sent over AJAX, only on pageload, which happens minimally on a React app.

**It seems that storing this information in localstorage makes more sense for our use case**
