### ISSUE TITLE
Technical Spike - Redux

### ISSUE THREAD

**Issue by astroash** [astroash/policy-picker#8]
Research Redux to see if it is worth the time investment to learn.

**Comment by maxgerber** [comment]
_Talk with Elias:_

+ Q: Is there any reason to use Redux in our app?
A: What ends up happening quite quickly on the native State of React is that you end up with lots of bits of state in various sections of the component tree. What becomes difficult is making sure that those individual atoms of state remain consistent with each other.
Whereas, in Redux the centralised store becomes responsible for updating different elements of state.
In order to update "grandchildren components" from the uppermost state, we would have to pass a callback function down the component tree.

**Redux or Not Redux. That is the question...**

**Comment by maxgerber** [comment]
We have decided that Redux is too much of an undertaking for the remaining time we have on this project. Issue closed.
